### ISSUE TITLE
eslint:recommended

### ISSUE THREAD

**Issue by darrenmce** [360incentives/eslint-config-base#6]
I'm not sure if this a recent change, or a change at all. But it seems eslint has nothing by default, and they expose a configuration called `eslint:recommended` that you can extend to your config

i've found using it in combination with our base config to work great:

```json
{
  "extends": ["eslint:recommended", "base", "react", "es6"]
}

```

see the top paragraph in:

http://eslint.org/docs/rules/

maybe `eslint:recommended` belongs in our baseline?

this makes #4 and #5 unnecessary

**Comment by snypelife** [comment]
do it up :+1:
